import { Category, Product, Purchase, PersonalUsage, DailyStockOpname, StockAdjustment, StockMovement } from '@/types';
import { getTodayDateString } from '../utils';

export const initialCategories: Category[] = [
  { id: 'cat-1', name: 'Rokok' },
  { id: 'cat-2', name: 'Sembako' },
  { id: 'cat-3', name: 'Minuman' },
  { id: 'cat-4', name: 'Makanan Ringan' },
  { id: 'cat-5', name: 'Bumbu & Mie Instan' },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    category_id: 'cat-1',
    category_name: 'Rokok',
    name: 'Rokok A (Sampoerna Mild)',
    base_unit: 'Batang',
    minimum_stock: 32,
    is_active: true,
    current_stock_base: 153, // 9 bungkus + 9 batang
    image_url: 'https://images.unsplash.com/photo-1527016016493-4ede2325b591?w=300&auto=format&fit=crop&q=60',
    units: [
      {
        id: 'unit-1-1',
        product_id: 'prod-1',
        unit_name: 'Batang',
        conversion_to_base: 1,
        cost_price: 1500,
        selling_price: 2000,
        is_default: false,
      },
      {
        id: 'unit-1-2',
        product_id: 'prod-1',
        unit_name: 'Bungkus',
        conversion_to_base: 16,
        cost_price: 24000,
        selling_price: 27000,
        is_default: true,
      },
    ],
  },
  {
    id: 'prod-2',
    category_id: 'cat-5',
    category_name: 'Bumbu & Mie Instan',
    name: 'Indomie Goreng',
    base_unit: 'Pcs',
    minimum_stock: 20,
    is_active: true,
    current_stock_base: 58,
    image_url: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=300&auto=format&fit=crop&q=60',
    units: [
      {
        id: 'unit-2-1',
        product_id: 'prod-2',
        unit_name: 'Pcs',
        conversion_to_base: 1,
        cost_price: 2800,
        selling_price: 3500,
        is_default: true,
      },
      {
        id: 'unit-2-2',
        product_id: 'prod-2',
        unit_name: 'Dus',
        conversion_to_base: 40,
        cost_price: 110000,
        selling_price: 135000,
        is_default: false,
      },
    ],
  },
  {
    id: 'prod-3',
    category_id: 'cat-3',
    category_name: 'Minuman',
    name: 'Teh Botol Sosro',
    base_unit: 'Botol',
    minimum_stock: 12,
    is_active: true,
    current_stock_base: 32,
    image_url: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=300&auto=format&fit=crop&q=60',
    units: [
      {
        id: 'unit-3-1',
        product_id: 'prod-3',
        unit_name: 'Botol',
        conversion_to_base: 1,
        cost_price: 3500,
        selling_price: 5000,
        is_default: true,
      },
      {
        id: 'unit-3-2',
        product_id: 'prod-3',
        unit_name: 'Krat',
        conversion_to_base: 24,
        cost_price: 80000,
        selling_price: 110000,
        is_default: false,
      },
    ],
  },
  {
    id: 'prod-4',
    category_id: 'cat-2',
    category_name: 'Sembako',
    name: 'Minyak Goreng Bimoli 1L',
    base_unit: 'Pcs',
    minimum_stock: 6,
    is_active: true,
    current_stock_base: 14,
    image_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=60',
    units: [
      {
        id: 'unit-4-1',
        product_id: 'prod-4',
        unit_name: 'Pcs',
        conversion_to_base: 1,
        cost_price: 16500,
        selling_price: 19000,
        is_default: true,
      },
      {
        id: 'unit-4-2',
        product_id: 'prod-4',
        unit_name: 'Dus',
        conversion_to_base: 12,
        cost_price: 190000,
        selling_price: 220000,
        is_default: false,
      },
    ],
  },
  {
    id: 'prod-5',
    category_id: 'cat-2',
    category_name: 'Sembako',
    name: 'Telur Ayam Negeri',
    base_unit: 'Butir',
    minimum_stock: 32,
    is_active: true,
    current_stock_base: 96,
    image_url: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=300&auto=format&fit=crop&q=60',
    units: [
      {
        id: 'unit-5-1',
        product_id: 'prod-5',
        unit_name: 'Butir',
        conversion_to_base: 1,
        cost_price: 1700,
        selling_price: 2200,
        is_default: false,
      },
      {
        id: 'unit-5-2',
        product_id: 'prod-5',
        unit_name: 'Kg',
        conversion_to_base: 16,
        cost_price: 26000,
        selling_price: 31000,
        is_default: true,
      },
    ],
  },
  {
    id: 'prod-6',
    category_id: 'cat-3',
    category_name: 'Minuman',
    name: 'Kopi Kapal Api Mix',
    base_unit: 'Sachet',
    minimum_stock: 20,
    is_active: true,
    current_stock_base: 45,
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=60',
    units: [
      {
        id: 'unit-6-1',
        product_id: 'prod-6',
        unit_name: 'Sachet',
        conversion_to_base: 1,
        cost_price: 1200,
        selling_price: 1800,
        is_default: true,
      },
      {
        id: 'unit-6-2',
        product_id: 'prod-6',
        unit_name: 'Pak (10 Sachet)',
        conversion_to_base: 10,
        cost_price: 11500,
        selling_price: 16000,
        is_default: false,
      },
    ],
  },
];

export const initialPurchases: Purchase[] = [
  {
    id: 'pur-1',
    date: getTodayDateString(),
    total_cost: 230000,
    note: 'Belanja stok grosir pagi hari',
    items: [
      {
        id: 'pur-item-1',
        purchase_id: 'pur-1',
        product_id: 'prod-1',
        product_name: 'Rokok A (Sampoerna Mild)',
        product_unit_id: 'unit-1-2',
        unit_name: 'Bungkus',
        quantity: 5,
        quantity_base: 80,
        cost_price: 24000,
        subtotal: 120000,
      },
      {
        id: 'pur-item-2',
        purchase_id: 'pur-2',
        product_id: 'prod-2',
        product_name: 'Indomie Goreng',
        product_unit_id: 'unit-2-2',
        unit_name: 'Dus',
        quantity: 1,
        quantity_base: 40,
        cost_price: 110000,
        subtotal: 110000,
      },
    ],
    created_at: new Date().toISOString(),
  },
];

export const initialPersonalUsages: PersonalUsage[] = [
  {
    id: 'pu-1',
    type: 'BARANG',
    product_id: 'prod-1',
    product_name: 'Rokok A (Sampoerna Mild)',
    product_unit_id: 'unit-1-1',
    unit_name: 'Batang',
    quantity: 2,
    quantity_base: 2,
    date: getTodayDateString(),
    note: 'Pemilik merokok saat siang hari',
    created_at: new Date().toISOString(),
  },
  {
    id: 'pu-2',
    type: 'UANG_CASH',
    amount_cash: 15000,
    date: getTodayDateString(),
    note: 'Ambil uang di laci untuk beli makan siang Nasi Padang di luar',
    created_at: new Date().toISOString(),
  },
];

export const initialDailyStockOpnames: DailyStockOpname[] = [
  {
    id: 'opname-prev-1',
    date: '2026-09-05',
    status: 'COMPLETED',
    total_omzet: 485000,
    total_modal: 362000,
    total_laba: 123000,
    total_terjual_base: 142,
    total_personal_cash: 15000,
    items: [
      {
        id: 'op-item-1',
        stock_opname_id: 'opname-prev-1',
        product_id: 'prod-1',
        product_name: 'Rokok A (Sampoerna Mild)',
        system_stock_base: 180,
        physical_stock_base: 153,
        difference_base: 27,
        personal_use_base: 2,
        calculated_sales_base: 25,
        selling_amount: 50000,
        cost_amount: 37500,
        profit_amount: 12500,
      },
    ],
    created_at: new Date('2026-09-05T21:00:00Z').toISOString(),
  },
];

export const initialStockAdjustments: StockAdjustment[] = [];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'mov-1',
    product_id: 'prod-1',
    product_name: 'Rokok A (Sampoerna Mild)',
    quantity_base: 80,
    movement_type: 'PURCHASE',
    reference_id: 'pur-1',
    date: getTodayDateString(),
    note: 'Barang Masuk (5 Bungkus)',
  },
];
